sudo: required
python:
  - 2.7
os:
  - linux
  - osx
install:
  - sudo pip install ansible
  - ansible-galaxy install -r requirements.yml -p ..
script: ansible-playbook tests/test.yml -i tests/inventory
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
